### ISSUE TITLE
http 501 error

### ISSUE THREAD

**Issue by starsmall-xiaoqq** [apache/openwhisk-composer#59]
I ran the demo example and got the error.
>deploy -i -w demo demo.json
OpenWhiskError: PUT https://apihost:port/api/v1/namespaces/_/actions/authenticate Returned HTTP 501 (Not Implemented) --> "Response Missing Error Message."
    at Client.handleErrors (/usr/local/lib/node_modules/openwhisk-composer/node_modules/openwhisk/lib/client.js:216:11)
    at /usr/local/lib/node_modules/openwhisk-composer/node_modules/openwhisk/lib/client.js:147:58

Did I miss any openwhisk setting  in server?

**Comment by tardieu** [comment]
You need to specify the concrete apihost:port for the openwhisk instance you are using. Something like:
```
deploy -i -w demo demo.json --apihost us-south.functions.cloud.ibm.com
```
You are probably also missing the authorization key.
```
deploy -i -w demo demo.json --apihost us-south.functions.cloud.ibm.com --auth myAuthKey
```

**Comment by starsmall-xiaoqq** [comment]
> You need to specify the concrete apihost:port for the openwhisk instance you are using. Something like:
> 
> ```
> deploy -i -w demo demo.json --apihost us-south.functions.cloud.ibm.com
> ```
> 
> You are probably also missing the authorization key.
> 
> ```
> deploy -i -w demo demo.json --apihost us-south.functions.cloud.ibm.com --auth myAuthKey
> ```

i have used "deploy -i -w demo demo.json --apihost myhost:443 --auth 23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP 

but the same error is generated. I can use wsk to create and invoke action.

**Comment by starsmall-xiaoqq** [comment]
> > You need to specify the concrete apihost:port for the openwhisk instance you are using. Something like:
> > ```
> > deploy -i -w demo demo.json --apihost us-south.functions.cloud.ibm.com
> > ```
> > 
> > 
> > You are probably also missing the authorization key.
> > ```
> > deploy -i -w demo demo.json --apihost us-south.functions.cloud.ibm.com --auth myAuthKey
> > ```
> 
> i have used "deploy -i -w demo demo.json --apihost myhost:443 --auth 23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
> 
> but the same error is generated. I can use wsk to create and invoke action. By the way,  I do not know wether or not , and where to set the following SSL configration:
> {
> "$composer": {
> "openwhisk": {
> "ignore_certs": true
> }
> },
> ...
> }

**Comment by starsmall-xiaoqq** [comment]
I have checked and changed proxy, it is confirm that --apihost myhost:80 (instead of :443) can get correct responses.
